import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import Header from "@/components/Header";
import SyncUserWithConvex from "@/components/SyncUserWithConvex";
import { Toaster } from "@/components/ui/toaster";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const clerkLocalization = {
  formFieldLabel__emailAddress: "Địa chỉ Email",
  badge__primary: "Chính",
  badge__thisDevice: "Thiết bị này",
  userButton: {
    action__manageAccount: "Thông tin tài khoản",
    action__signOut: "Đăng xuất",
    action__signOutAll: "Đăng xuất tất cả thiết bị",
    action__addAccount: "Thêm tài khoản",
  },
  userProfile: {
    formButtonReset: "Hủy",
    formButtonPrimary__save: "Lưu",
    formButtonPrimary__add: "Thêm",
    navbar:{
      title: "Tài khoản",
      description: "Quản lý thông tin tài khoản",
      account: "Thông tin tài khoản",
      security: "Bảo mật",
    },
    emailAddressPage:{
      title: "Thêm địa chỉ Email",
      formHint: "Bạn sẽ cần xác minh địa chỉ email này trước khi có thể thêm vào tài khoản của bạn",
    },
    start: {
      headerTitle__account: "Thông tin tài khoản",
      headerTitle__security: "Bảo mật tài khoản",
      activeDevicesSection:{
        title: "Thiết bị đang hoạt động",
      },
      profileSection:{
        title: "Thông tin tài khoản",
        primaryButton: "Cập nhật",
      },
      usernameSection:{
        title: "Username", 
        primaryButton__updateUsername: "Cập nhật",
      },
      emailAddressesSection:{
        title: "Email",
        destructiveAction: "Gỡ bỏ Email",
        primaryButton: "Thêm Email",
      },
      dangerSection:{
        title: "Xóa tài khoản",
        deleteAccountButton: "Xóa tài khoản",
      },
    },
    profilePage: {
      title: "Thông tin cá nhân",
      imageFormSubtitle: "Tải lên",
      imageFormDestructiveActionSubtitle: "Gỡ bỏ",
      fileDropAreaHint:"Khuyến khích kích thước 1:1, nhỏ hơn 10MB",
    },
    usernamePage: {
      title__set: "Đặt tên người dùng",
      title__update: "Cập nhật tên người dùng",
      primaryButton__setUsername: "Tạo tên người dùng",
      primaryButton__updateUsername: "Cập nhật tên người dùng",
    },
    deletePage: {
      title: "Xóa tài khoản",
      messageLine1: "Bạn có chắc muốn xóa tài khoản của bạn không?",
      messageLine2: "Thao tác này là vĩnh viễn và không thể hoàn tác.",
      actionDescription: "Nhập 'Delete account' bên dưới để xóa tài khoản",
      confirm: "Xóa tài khoản",
    },
    // emailAddressesPage: {
    //   title: "Email",
    //   primaryButton__addEmail: "Thêm email",
    //   detailsTitle__primary: "Email chính",
    //   detailsTitle__nonPrimary: "Email phụ",
    // },
    // securityPage: {
    //   title: "Thiết bị hoạt động",
    //   activeDevicesSection: {
    //     title: "Thiết bị đang hoạt động",
    //     detailsTitle: "Chi tiết thiết bị",
    //     thisDevice: "Thiết bị này",
    //     signOut: "Đăng xuất thiết bị",
    //   },
    //   dangerSection: {
    //     title: "Xóa tài khoản",
    //     deleteAccountButton: "Xóa tài khoản",
    //   },
    // },
  },
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <ConvexClientProvider>
          <ClerkProvider localization={clerkLocalization}>
            <Header />
            <SyncUserWithConvex />
            {children}


            <Toaster />
          </ClerkProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}